name: Publish

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.x

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      # Set working directory globally for the remaining steps to be ./packages/reutil
      - name: Set working directory
        run: echo "Working in ./packages/reutil"

      - name: Install dependencies
        working-directory: ./packages/reutil
        run: pnpm install --frozen-lockfile

      - name: Create Pull request or publish
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          publish: pnpm run release
          cwd: ./packages/reutil

      - name: Publish to npmjs
        if: steps.changesets.outputs.published == 'true'
        working-directory: ./packages/reutil
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
